### ISSUE TITLE
[SearchRouter] reset does not reset the selectbox properly

### ISSUE THREAD

**Issue by astroidex** [mapbender/mapbender#1214]
**Describe the bug**
If you have a SearchRouter configuration with Selectbox search works fine. But when you klick reset the selected option is still listed and the next search will assume that no value is selected.

**To Reproduce**
1. Create a searchRouter configuration with a selectbox

![Bildschirmfoto von 2019-10-30 15-04-18](https://user-images.githubusercontent.com/996298/67865154-208e3e00-fb27-11e9-8b24-e7fb04a28d88.png)

```
class: Mapbender\CoreBundle\Component\SQLSearchEngine
class_options:
  connection: search_db
  relation: brd.qry_gn250_p_ortslage
  attributes:
    - gid
    - name
    - gemeinde
    - hoehe_ger
  geometry_attribute: geom
form:
  name:
    type: text
    options:
      required: false
      label: Name
      attr:
        data-autocomplete: 'on'
    compare: ilike
  gemeinde:
    type: choice
    options:
      empty_value: 'Please select...'  
      choices: 
        'Bonn': Bonn
        'Bornheim': Bornheim
        'Köln': Köln
        'Siegburg': 'Siegburg'
      required: false     
results:
  view: table
  count: true
  headers:
    name: Name
    gemeinde: Gemeinde
    bundesland: Bundesland
    ewz_ger: Einwohner
    hoehe_ger: Höhe
  callback:
    event: click
    options:
      buffer: 1000
      minScale: null
      maxScale: null
  styleMap:
    default:
      strokeColor: '#00ff00'
      strokeOpacity: 1
      fillOpacity: 0
    select:
      strokeColor: '#ff00ff'
      fillColor: '#ff00ff'
      fillOpacity: 0.8
```

2. Search with selected option from selectbox -> see results
3. Reset -> see selectbox option is still selected
4. Search again -> all results are given back not only the filtered results

![Bildschirmfoto von 2019-10-30 15-05-25](https://user-images.githubusercontent.com/996298/67865166-26841f00-fb27-11e9-8903-fee02d21c898.png)

**Expected behavior**
Either 
* keep selected options after reset (only clear resultlist and inputfields)
* or clear the selectbox so the user notivces that the next search will not use the filter

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.0.8.4

**Screenshots / Logmessage**

**Data for SearchExample**

[qry_gn250_p_ortslage.txt](https://github.com/mapbender/mapbender/files/3789371/qry_gn250_p_ortslage.txt)

**Comment by astroidex** [comment]
I showed it to to @rschwammborn. He will reproduce the bug.

**Comment by rschwammborn** [comment]
Can confirm! I redirected the issue into our internal ticket system for the developers.

**Comment by astroidex** [comment]
@rschwammborn - could you please test the PR1216 https://github.com/mapbender/mapbender/pull/1216

**Comment by werrolf** [comment]
Fixed in b53e0dca97d327b337956f0fc5b1ed623387a373

**Comment by pfavero-wheregroup** [comment]
Bug is still reproducible in Mapbender-Starter Version 3.0.8.5
Merge Request: https://github.com/mapbender/mapbender/pull/1235
