### ISSUE TITLE
[digitizer] alway active when application opens

### ISSUE THREAD

**Issue by VarCharly** [mapbender/mapbender#1373]
**Describe the bug**
If you add the digitizer to an application with the options "displayOnInactive: false" and "displayPermanent: false" the element should be inactive at the start of the application (position: not first item in the sidepane). The digitizer is always active when the application opens. If you open the digitizer tab and then any other tab in the sidepane THEN it is inactive.  
See https://doc.mapbender3.org/en/functions/editing/digitizer.html#feature-basic-definition 

**To Reproduce**
1. Add the digitizer in the sidepane as the second item
**Expected behavior**
Inactive when application opens

**Versions (please complete the following information if it helps to narrow down the bug):**
 - Mapbender: 3.2.5
 - Browser Firefox/ Chrome

**Comment by astroidex** [comment]
Hi @VarCharly,

this bug was reported for 3.0.8.x before #1211. Looks like it was fixed for Version 3.0.8.5 for digitizer 1.1.x

Now we have digitizer 1.4.x

The Test team has to check.

**Comment by rschwammborn** [comment]
Hey @VarCharly & @astroidex ,

I just tested this and came to the same conclusion that the objects still appear on application start  - so I created an internal bug ticket.

Greetings!

**Comment by astroidex** [comment]
Tested with digitizer 1.4.9: works as expected.
