### ISSUE TITLE
Overview map: wrong extent

### ISSUE THREAD

**Issue by rschwammborn** [mapbender/mapbender#958]
The overview map does not react accordingly to srs changes in the main map.

See screenshot UTM/33N: Wuppertal/Canterbury

![Overviewmap](https://user-images.githubusercontent.com/21199730/41962036-541218d8-79f4-11e8-9088-971f71239c04.png)

**Comment by werrolf** [comment]
Correction: the overview map does not react to srs changes on the main map.  
Starting SRS is irrelevant.

**Comment by werrolf** [comment]
I've tried to implement SRS change behaviour for Overview today, but couln't do it. [There are some artefacts left in the code](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.element.overview.js#L230). Most of it disabled, save for a console log. Hopefully this is good enough a starting point so someone can get this working.

Bonus:
* [OL v4.6.5 overview map source code](https://github.com/openlayers/openlayers/blob/v4.6.5/src/ol/control/overviewmap.js)
* [OL v4.6.5 overview map reference documentation](https://openlayers.org/en/v4.6.5/apidoc/ol.control.OverviewMap.html)

**Comment by werrolf** [comment]
[Origin of the supplied event data for reference](https://github.com/mapbender/mapbender/blob/3eec74fa74ba0b14f64ca6ed1b3f11a7dcb628e5/src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.js#L207)

**Comment by werrolf** [comment]
Fixed now, thanks @philvanbwg

**Comment by AxxL** [comment]
@werrolf @philvanbwg  The issue still exists. See internal Server: http://ol4/ol4/application/test_map

Both Services are WMS 1.1.1

**Comment by eschuettler** [comment]
In order to get a better overview we moved all tickets regarding OL implementation to an internal management system.
Stay tuned!
